config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'

  get 'pages/home'

  get "/login" => "user_sessions#new", as: :login
  delete "/logout" => "user_sessions#destroy", as: :logout

  resources :users
  resources :user_sessions, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :recipes do
    put :email, on: :member
    resources :recipe do
      member do
        patch :complete
      end
    end
  end

  root 'recipes#index'


end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true
  validates :coffee, presence: true
  validates :water, presence: true
  validates :seconds, presence: true
  validates :description, presence: true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
#  before_action :require_user
  before_action :set_recipe, only: [:show, :edit, :update, :destroy, :email]
  before_action :set_back_link, except: [:index]
  before_filter :require_permission, only: [:edit, :destroy]


def require_permission
  if current_user != Recipe.find(params[:id]).user
    redirect_to recipe_path(@recipe), error: "You can only edit and delete your own recipes."
    #Or do something else here
  end
end

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = current_user.recipes.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, success: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, success: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def email
    destination = params[:to]
    notifier = Notifier.recipe(@recipe, destination)
    if destination =~ /@/ && notifier.deliver
      redirect_to recipe_path(@recipe), success: "Recipe sent."
    else
      redirect_to recipe_path(@recipe), error: "Recipe could not be sent."
    end
  end

  private
    def set_back_link
      go_back_link_to recipes_path
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :coffee, :water, :seconds, :description)
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_blank_slate.html.erb
<div class="row blank-slate">
  <div class="small-12 small-centered columns">
    <p>You don't have any recipes!</p>
    <%= link_to "Create Recipe", new_recipe_path, class: "button radius" %>
  </div>
</div>

app/views/recipes/_form.html.erb
<%= form_for(@recipe, builder: FoundationFormBuilder) do |f| %>

  <%= f.text_field :title, label: "Recipe Title", autofocus: "autofocus" %>
  <%= f.number_field :coffee, label: "Coffee (grams)" %>
  <%= f.number_field :water, label: "Water (ml)" %>
  <%= f.number_field :seconds, label: "Brewing time (seconds)" %>
  <%= f.text_field :description %>

  <%= f.submit "Save", class: "button radius expand" %>

<% end %>

app/views/recipes/_recipe.html.erb
<li id="<%= dom_id(recipe) %>" class="clearfix">



  <%= link_to recipe, class: "row" do %>

    <div class="small-4 columns title-list truncate" title="<%= recipe.title %>"><%= recipe.title %></div>
    <div class="small-4 columns coffee-list truncate" title="<%= recipe.coffee %>"><%= recipe.coffee %> grams</div>
    <div class="small-4 columns water-list truncate" title="<%= recipe.water %>"><%= recipe.water %>ml</div>
  <% end %>

</li>

app/views/recipes/edit.html.erb
<%= title "Editing #{@recipe.title}" %>

<%= render 'form' %>

app/views/recipes/index.html.erb
<%= title "Recipes" %>


<% if @recipes.size > 0 %>

  <div class="row">

    <% if logged_in? %>
      <div class="small-12 columns truncate index-header">Your recipes</div>
      <div class="small-4 columns header title-index truncate"><h5>Title</h5></div>
      <div class="small-4 columns header coffee-index truncate"><h5>Coffee</h5></div>
      <div class="small-4 columns header water-index truncate"><h5>Water</h5></div>

      <ul class="list no-bullet">

        <div class="index">
          <%= render partial: "recipe", collection: current_user.recipes %>
        </div>
      </ul>
    <% end %>

      <div class="small-12 columns truncate index-header">All recipes</div>
      <div class="small-4 columns header title-index truncate"><h5>Title</h5></div>
      <div class="small-4 columns header coffee-index truncate"><h5>Coffee</h5></div>
      <div class="small-4 columns header water-index truncate"><h5>Water</h5></div>

    <ul class="list no-bullet">

      <div class="index">
        <%= render partial: "recipe", collection: @recipes.sort { |a,b| a.title.downcase <=> b.title.downcase } %>
      </div>
    </ul>
  </div>


<% else %>
  <%= render partial: 'blank_slate' %>
<% end %>

app/views/recipes/new.html.erb
<%= title "Add Recipe" %>

<%= render 'form' %>

app/views/recipes/show.html.erb
<audio src="<%= asset_path('alarm.mp3') %>"></audio>

<script>
var timer = '<%= @recipe.seconds %>'
var audio = document.getElementsByTagName("audio")[0];
var timeout;


jQuery(document).on("ready page:load", function() {

	$(function () {

		$('#defaultCountdown').countdown({
															until: timer,	format: 'MS'});

		$('#defaultCountdown').countdown('pause')

		$( "#start" ).click(function() {
			window.clearTimeout(timeout);
			timeout = window.setTimeout(function(){audio.play()}, timer * 1000);
			$('#defaultCountdown').countdown('resume')
			setTimeout(function() { $('#defaultCountdown').countdown('option','until', timer)})
		});

		$("#pause").click(function() {
			window.clearTimeout(timeout);
			$('#defaultCountdown').countdown('toggle')
		});


	});
});




</script>



<%= content_for(:title) do %><%= @recipe.title %> | <% end %>
<div class="row collapse recipe-title">
  <div class="small-11 columns">
    <h2 class="page-title truncate"><%= @recipe.title %></h2>
  </div>
  <div class="small-1 columns">
    <span class="fa fa-caret-down">
  </div>
</div>

<div class="row hide" id="recipe-functions">
  <div class="small-4 columns">
    <%= link_to edit_recipe_path(@recipe), class: "button expand radius outline" do %>
    <span class="fa fa-edit"></span>
    Edit
    <% end %>
  </div>
  <div class="small-4 columns">

    <%= link_to recipe_path(@recipe), class: "button expand radius outline", data: { "reveal-id" => "email-modal" } do %>
    <span class="fa fa-envelope-o"></span>
    Email
    <% end %>
  </div>
  <div class="small-4 columns">
    <%= link_to recipe_path(@recipe), class: "button expand radius outline alert", method: :delete, data: {confirm: "Are you sure you want to delete this recipe? There is no undo."} do %>
    <span class="fa fa-trash-o"></span>
    Delete
    <% end %>
  </div>
</div>

  <div class="row">
    <div class="small-12 columns countdown">

      <div id="defaultCountdown"></div>
    </div>

  <div class="row">
    <div class="small-12 columns description">
      <%= @recipe.description %>
    </div>
  </div>

  <div class="row">
    <div class="small-6 start button text-center columns" id="start">
      <h4>Start/Reset</h4>
    </div>

    <div class="small-6 pause button text-center columns" id="pause">
      <h4>Pause/Resume</h4>
    </div>
  </div>

  <div class="row">
    <div class="small-4 columns recipe">
      <div class="text-center expand coffee"><h4>Coffee</h4>
      <h3><%= @recipe.coffee %></h3> <h5>grams</h5>
      </div>
    </div>

    <div class="small-4 columns recipe">
      <div class="text-center expand water"><h4>Water</h4>
      <h3><%= @recipe.water %></h3> <h5>ml</h5>
      </div>
    </div>

    <div class="small-4 columns recipe">
      <div class="text-center expand seconds"><h4>Brew</h4>
      <h3><%= @recipe.seconds %></h3> <h5>seconds</h5>
      </div>
    </div>
  </div>

<div id="email-modal" class="reveal-modal tiny" data-reveal>
  <a class="close-reveal-modal">&#215;</a>
  <%= form_tag email_recipe_path(@recipe), method: :put do %>
    <%= label_tag :destination, "what email address would you like to send this to?" %>
    <%= text_field_tag :destination %>
    <br />
    <%= submit_tag "Send Recipe", class: "button radius medium expand submit" %>
  <% end %>
</div>