config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'

  get 'pages/home'

  get "/login" => "user_sessions#new", as: :login
  delete "/logout" => "user_sessions#destroy", as: :logout

  resources :users
  resources :user_sessions, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :recipes do
    put :email, on: :member
    resources :recipe do
      member do
        patch :complete
      end
    end
  end

  root 'recipes#index'


end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <div data-alert class="flash alert-box text-center <%= type %>">
    <%= message %>
    <a href="#" class="close">&times;</a>
  </div>
<% end %>

app/views/layouts/_header.erb
<div class="small-4 columns header-icon">
  <% if @go_back_link_to %>
    <%= link_to "Back", @go_back_link_to, class: "icon-arrow-left hide-text" %>
  <% else %>
    <% if logged_in? %>
      <%= link_to "Sign Out", logout_path, method: :delete, class: "icon-signout hide-text" %>
    <% end %>
  <% end %>
</div>
<div class="small-4 columns">
  <h1 class="logo"><%= link_to image_tag('coffeefilter.png'), recipes_path %></h1>
</div>
<div class="small-4 columns header-icon">
  <% if logged_in? %>
    <%= new_recipe_link %>
  <% end %>
</div>

app/views/layouts/_header_logged_in.html.erb
<div class="small-4 columns header-icon">

  <% if @go_back_link_to %>
    <%= link_to "Back", @go_back_link_to, class: "icon-arrow-left hide-text" %>
  <% else %>
  <%= link_to "Sign Out", logout_path, method: :delete, class: "icon-signout hide-text" %>
  <% end %>
</div>
<div class="small-4 columns">
  <h1 class="logo"><%= link_to "aeropressTimer", recipes_path, class: "hide-text" %></h1>
</div>
<div class="small-4 columns header-icon">
  <%= new_recipe_link %>
</div>

app/views/layouts/_header_logged_out.html.erb
<div class="small-12 columns header-icon">
  <%= link_to "Sign In", new_user_session_path %> -
  <%= link_to "Sign Up", new_user_path %>
</div>
<div class="small-12 columns header-icon">
  <br />
  <%= link_to "About", pages_about_path %>
</div>
<div class="small-4 columns">
  <h1 class="logo"><%= link_to "aeropressTimer", root_path, class: "hide-text" %></h1>
</div>
<div class="small-4 columns header-icon">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %>coffeeFilter</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

  <%= render partial: "layouts/flash" %>




  <header class="row global-header">
    <div class="small-12 small-centered medium-8 medium-centered large-6 large-centered columns">
      <%= render partial: 'layouts/header' %>
    </div>
  </header>


  <div class="row collapse">
    <div class="small-12 small-centered medium-8 medium-centered large-6 large-centered columns">
      <%= yield %>
    </div>
  </div>

  <footer class="row global-footer">
    <div class="small-6 medium-8 small-push-3 medium-push-0 text-center medium-centered large-6 columns">
      <% if logged_in? %>
        <%= link_to "Settings", edit_user_path(current_user) %> - <%= link_to "About", pages_about_path %>
      <% else %>
        <%= render partial: 'layouts/header_logged_out' %>
      <% end %>
    </div>

  <footer>

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>coffeeFilter</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: "layouts/flash" %>


  <header class="row global-header">
    <div class="small-12 small-centered columns">
      <%= render partial: "layouts/header_logged_out" %>
    </div>
  </header>

  <%= yield %>

  <footer class="row global-footer">
    <div class="small-12 small-centered columns text-center">
      <%= link_to "Already have an account? Sign in.", login_path %>
    </div>
  <footer>

</body>
</html>